# Generated by Django 4.2.4 on 2024-11-08 02:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(verbose_name='Fecha de cita')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizado')),
                ('description_customer', models.TextField(blank=True, null=True, verbose_name='Descripción de cliente')),
                ('inprogress', models.BooleanField(default=False, verbose_name='En ejecución')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'Cita',
            },
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention', models.TimeField(verbose_name='Atención')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'db_table': 'Atención',
            },
        ),
        migrations.CreateModel(
            name='ConfigConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('value', models.IntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Constante',
                'verbose_name_plural': 'Constantes',
                'db_table': 'Constante',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('description_small', models.CharField(max_length=255, verbose_name='Descripción pequeña')),
                ('image_description', models.ImageField(default='index/mantenimiento.png', upload_to='index/', verbose_name='Imágen')),
                ('have_constant', models.BooleanField(default=False, verbose_name='Tiene Constante')),
            ],
            options={
                'verbose_name': 'Descripción',
                'verbose_name_plural': 'Descripciones',
                'db_table': 'Descripción',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_job', models.TextField(blank=True, null=True, verbose_name='Descripción trabajo')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.appointment', verbose_name='Id_Cita')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'db_table': 'Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=20, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(limit_value=9)], verbose_name='Teléfono')),
                ('specialty', models.CharField(blank=True, choices=[('mecanico', 'Mecánico'), ('electrico', 'Eléctrico')], max_length=50, verbose_name='Especialidad')),
                ('image', models.ImageField(default='mechanics/foto_personal.jpg', upload_to='mechanics/', verbose_name='Imágen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Mecánico',
                'verbose_name_plural': 'Mecánicos',
                'db_table': 'Mecánico',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('earn_points', models.PositiveIntegerField(verbose_name='Puntos por servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='TitleHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_header', models.CharField(max_length=50, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'db_table': 'Título',
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('num_address', models.IntegerField(verbose_name='Número dirección')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'Sucursal',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_service', models.BooleanField(default=False, verbose_name='Estado de servicio')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.job', verbose_name='Id_Trabajo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.service', verbose_name='Id_Servicio')),
            ],
            options={
                'verbose_name': 'Servicio por trabajo',
                'verbose_name_plural': 'Servicios por trabajo',
                'db_table': 'Servicio por trabajo',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('patent', models.CharField(max_length=6, verbose_name='Patente')),
                ('year', models.PositiveIntegerField(default=0, verbose_name='Año')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'Vehículo',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Punto',
                'verbose_name_plural': 'Puntos',
                'db_table': 'Punto',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.vehiclestatus', verbose_name='Id_Estado'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=50, unique=True, verbose_name='Cupón')),
                ('valid', models.BooleanField(default=True, verbose_name='Válido')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'db_table': 'Cupón',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.PositiveIntegerField(default=0, verbose_name='Kilometraje')),
                ('gasoline_tank', models.CharField(choices=[('1', '1/4'), ('2', '2/4'), ('3', '3/4'), ('4', 'Full')], default='0', max_length=30, verbose_name='Tanque de gasolina')),
                ('front_lights', models.BooleanField(default=False, verbose_name='Luces delanteras')),
                ('rear_lights', models.BooleanField(default=False, verbose_name='Luces traseras')),
                ('chassis', models.BooleanField(default=False, verbose_name='Chasis')),
                ('cleaning', models.BooleanField(default=False, verbose_name='Limpieza')),
                ('extinguisher', models.BooleanField(default=False, verbose_name='Extinguidor')),
                ('first_aid_kit', models.BooleanField(default=False, verbose_name='Botiquin')),
                ('triangles', models.BooleanField(default=False, verbose_name='Triángulos')),
                ('hydraulic_jack', models.BooleanField(default=False, verbose_name='Gato hidráulico')),
                ('spare_wheel', models.BooleanField(default=False, verbose_name='Rueda repuesto')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Management.job', verbose_name='Id_Trabajo')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'db_table': 'Checklist',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='attention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.attention', verbose_name='Atención'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Management.mechanic', verbose_name='Mecánico'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Management.vehicle', verbose_name='Data vehículo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.workshop', verbose_name='Sucursal'),
        ),
    ]
