# Generated by Django 4.2.4 on 2023-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='gasoline_tank',
            field=models.CharField(choices=[('1/4', '1/4'), ('2/4', '2/4'), ('3/4', '3/4'), ('Full', 'Full')], default='0', max_length=30, verbose_name='Tanque de bencina'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='km',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje'),
        ),
    ]
