# Generated by Django 4.2.4 on 2023-12-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_checklist_gasoline_tank_checklist_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Management.mechanic', verbose_name='Mecánico'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='gasoline_tank',
            field=models.CharField(choices=[('1/4', '1/4'), ('2/4', '2/4'), ('3/4', '3/4'), ('Full', 'Full')], default='0', max_length=30, verbose_name='Tanque de gasolina'),
        ),
    ]
