# Generated by Django 4.2.4 on 2023-11-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_description_titleheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
