# Generated by Django 4.2.4 on 2023-11-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_configconstants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigConstants',
            new_name='ConfigConstant',
        ),
    ]
