# Generated by Django 4.2.4 on 2023-11-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_rename_configconstants_configconstant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='image_description',
            field=models.ImageField(default='index/mantenimiento.PNG', upload_to='index/'),
        ),
    ]
