# Generated by Django 4.2.4 on 2023-11-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_alter_description_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='have_constant',
            field=models.BooleanField(default=False),
        ),
    ]
