# Generated by Django 4.2.4 on 2023-11-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_description_have_constant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
