# Generated by Django 4.2.4 on 2023-11-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_mechanic_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
