# Generated by Django 4.2.4 on 2023-11-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_vehicle_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name_plural': 'Cita'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='attention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.attention', verbose_name='Atención'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizado'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_register',
            field=models.DateField(verbose_name='Fecha de cita'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description_customer',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='inprogress',
            field=models.BooleanField(default=False, verbose_name='En ejecución'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.mechanic', verbose_name='Mecánico'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Management.vehicle', verbose_name='Data vehículo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.workshop', verbose_name='Taller'),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='Cita',
        ),
    ]
