# Generated by Django 4.2.4 on 2023-11-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='num_addres',
            new_name='num_address',
        ),
    ]
