# Generated by Django 4.2.4 on 2023-11-21 18:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0010_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attention',
            options={'verbose_name': 'Atención', 'verbose_name_plural': 'Atenciones'},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupón', 'verbose_name_plural': 'Cupones'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Descripción', 'verbose_name_plural': 'Descripciones'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterModelOptions(
            name='mechanic',
            options={'verbose_name': 'Mecánico', 'verbose_name_plural': 'Mecánicos'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Punto', 'verbose_name_plural': 'Puntos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='titleheader',
            options={'verbose_name': 'Título', 'verbose_name_plural': 'Títulos'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterModelOptions(
            name='vehiclestatus',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Servicio por trabajo', 'verbose_name_plural': 'Servicios por trabajo'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.AlterField(
            model_name='attention',
            name='attention',
            field=models.TimeField(verbose_name='Atención'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='chassis',
            field=models.BooleanField(default=False, verbose_name='Chasis'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cleaning',
            field=models.BooleanField(default=False, verbose_name='Limpieza'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='extinguisher',
            field=models.BooleanField(default=False, verbose_name='Extinguidor'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='first_aid_kit',
            field=models.BooleanField(default=False, verbose_name='Botiquin'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='front_lights',
            field=models.BooleanField(default=False, verbose_name='Luces delanteras'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='hydraulic_jack',
            field=models.BooleanField(default=False, verbose_name='Gato hidráulico'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Management.job', verbose_name='Id_Trabajo'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='rear_lights',
            field=models.BooleanField(default=False, verbose_name='Luces traseras'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='spare_wheel',
            field=models.BooleanField(default=False, verbose_name='Rueda repuesto'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='triangles',
            field=models.BooleanField(default=False, verbose_name='Triángulos'),
        ),
        migrations.AlterField(
            model_name='configconstant',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='configconstant',
            name='value',
            field=models.IntegerField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon',
            field=models.CharField(max_length=50, unique=True, verbose_name='Cupón'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Válido'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description_small',
            field=models.CharField(max_length=255, verbose_name='Descripción pequeña'),
        ),
        migrations.AlterField(
            model_name='description',
            name='have_constant',
            field=models.BooleanField(default=False, verbose_name='Tiene Constante'),
        ),
        migrations.AlterField(
            model_name='description',
            name='image_description',
            field=models.ImageField(default='index/mantenimiento.PNG', upload_to='index/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='job',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.appointment', verbose_name='Id_Cita'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description_job',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción trabajo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.vehiclestatus', verbose_name='Id_Estado'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='image',
            field=models.ImageField(default='mechanics/foto_personal.jpg', upload_to='mechanics/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.CharField(max_length=9, validators=[django.core.validators.MaxLengthValidator(limit_value=9)], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Mecánico', 'Mecánico'), ('Eléctrico', 'Eléctrico')], max_length=50, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='point',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='point',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='service',
            name='earn_points',
            field=models.PositiveIntegerField(verbose_name='Puntos por servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='titleheader',
            name='title_header',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='patent',
            field=models.CharField(max_length=10, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=0, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='work',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.job', verbose_name='Id_Trabajo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.service', verbose_name='Id_Servicio'),
        ),
        migrations.AlterField(
            model_name='work',
            name='status_service',
            field=models.BooleanField(default=False, verbose_name='Estado de servicio'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='num_address',
            field=models.IntegerField(verbose_name='Número dirección'),
        ),
        migrations.AlterModelTable(
            name='attention',
            table='Atención',
        ),
        migrations.AlterModelTable(
            name='checklist',
            table='Checklist',
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='Cupón',
        ),
        migrations.AlterModelTable(
            name='description',
            table='Descripción',
        ),
        migrations.AlterModelTable(
            name='job',
            table='Trabajo',
        ),
        migrations.AlterModelTable(
            name='mechanic',
            table='Mecánico',
        ),
        migrations.AlterModelTable(
            name='point',
            table='Punto',
        ),
        migrations.AlterModelTable(
            name='service',
            table='Servicio',
        ),
        migrations.AlterModelTable(
            name='titleheader',
            table='Título',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='Vehículo',
        ),
        migrations.AlterModelTable(
            name='vehiclestatus',
            table='Estado',
        ),
        migrations.AlterModelTable(
            name='work',
            table='Servicio por trabajo',
        ),
        migrations.AlterModelTable(
            name='workshop',
            table='Taller',
        ),
    ]
