# Generated by Django 4.2.4 on 2023-11-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_alter_attention_options_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configconstant',
            options={'verbose_name': 'Constante', 'verbose_name_plural': 'Constantes'},
        ),
    ]
